# Generated by Django 4.2.1 on 2023-05-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interlude', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='music',
        ),
    ]
