# Generated by Django 4.2.1 on 2023-05-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlude', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
