# Generated by Django 4.2.1 on 2023-06-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlude', '0006_followerscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='post_images'),
        ),
    ]
