# Generated by Django 4.2.1 on 2023-06-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlude', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to=''),
        ),
    ]
