# Generated by Django 4.2.1 on 2023-06-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interlude', '0009_post_userimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userimg',
        ),
    ]
