# Generated by Django 4.2.1 on 2023-06-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlude', '0017_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userpp',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
